# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/.devcontainer/"
    schedule:
      interval: "daily"
    assignees:
    - "microsoft/mlos-committers"
  - package-ecosystem: "pip"
    directory: "/mlos_core/"
    schedule:
      interval: "daily"
    assignees:
    - "microsoft/mlos-committers"
  - package-ecosystem: "pip"
    directory: "/mlos_bench/"
    schedule:
      interval: "daily"
    assignees:
    - "microsoft/mlos-committers"
