version: '3.8'

services:
  app:
    build:
      context: ./tmp
      dockerfile: ../Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      cache_from:
        - mloscore.azurecr.io/mlos-core-devcontainer:latest

    volumes:
      - ../..:/workspaces:cached

    env_file: ../.env

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while true; do sleep 1000; done"

  docs-www:
    build:
      context: ./tmp
      dockerfile: ../../doc/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        NGINX_PORT: ${NGINX_PORT}

    env_file: ../.env

    restart: unless-stopped
    volumes:
      # Our nginx config overrides the default listening port and serving directory.
      - ../doc:/doc
      - ../doc/nginx-default.conf:/etc/nginx/templates/default.conf.template

    # Add "forwardPorts": ["81"] to **devcontainer.json** to forward nginx locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
