# MLOS continuous integration pipelines:
#
# - Build/Test on Windows
# - Build/Test Ubuntu 16.04, 18.04, 20.04
#   (using docker images which also get published on success)
# - Check for license headers
# - Generate a static website (and link check it)

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run the debug/retail msbuild jobs separately so they can be executed in parallel.

  windows-msbuild:
    name: Run ${{ matrix.configuration }} msbuild on Windows
    runs-on: windows-2019
    timeout-minutes: 20
    strategy:
      matrix:
        configuration: [Debug, Release]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs multiple commands using the runners shell
    - name: Run ${{ matrix.configuration }} msbuild
      timeout-minutes: 15
      shell: cmd
      run: |
        set Configuration=${{ matrix.configuration }}
        scripts\build.windows.cmd

  # Docker build process overview:
  # - We currently use the docker.pkg.github.com package registry as a staging
  # ground to cache the ":latest" version of the build image.
  # - For authentication we use the built-in GITHUB_TOKEN secret to avoid the
  # need to setup special secrets (see forked repo considerations below).
  # Once it adds GITHUB_TOKEN supported, we will switch the pipelines to use
  # the recently announced ghcr.io registry.
  # - To support forked repos also executing the actions workflows (e.g. for
  # local testing), we use variables and target the local fork's package registry.
  # - For each PR, we rebuild the images using a combination of local action
  # caching layer, the upstream ":latest" image, and the local fork's ":latest"
  # image and tag the result using the ":git-sha" in the local cache.
  # - Images are not pushed to the package registry until all of the tests pass.
  # - To support parallel testing, we need to "rebuild" the image in several
  # steps (hence the caches).
  # - TODO: In a separate workflow, we nightly do a clean rebuild without any caches
  # (again running tests before pushing it).
  # - By only pushing the "latest" we reduce the burden of having the garbage
  # collect any old images that were published using the git-sha.

  # docker only recognizes lower case registry names and doesn't provide a native function,
  # so we need to perform a small shell transformation
  docker-registry-name:
    name: Compute the lowercase github docker package registry name
    runs-on: ubuntu-latest
    outputs:
      tolower: ${{ steps.tolower.outputs.registry_name }}
    steps:
    - id: tolower
      shell: bash
      run: echo "::set-output name=registry_name::docker.pkg.github.com/${{ github.repository }}" | tr A-Z a-z

  docker-image-fresh-build:
    name: Build fresh Ubuntu ${{ matrix.UbuntuVersion }} image
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        UbuntuVersion: [16.04, 18.04, 20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        build-args: UbuntuVersion=${{ matrix.UbuntuVersion }}
        tags: mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
        # Force a fresh build
        no-cache: true
        pull: true
        #cache-from: (none)
        cache-to: type=local,dest=/tmp/.buildx-cache
        #load: true

  docker-image-cached-build:
    name: Build Ubuntu ${{ matrix.UbuntuVersion }} image (cache)
    runs-on: ubuntu-latest
    needs: [docker-image-fresh-build, docker-registry-name]
    timeout-minutes: 20
    strategy:
      matrix:
        UbuntuVersion: [16.04, 18.04, 20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        build-args: UbuntuVersion=${{ matrix.UbuntuVersion }}
        tags: mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
          docker.pkg.github.com/microsoft/mlos/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
        cache-to: type=local,dest=/tmp/.buildx-cache
        load: true

  linux-build-test:
    name: Ubuntu ${{ matrix.UbuntuVersion }} ${{ matrix.configuration }} build/test C++/C#
    runs-on: ubuntu-latest
    needs: [docker-registry-name, docker-image-cached-build]
    timeout-minutes: 30
    strategy:
      matrix:
        UbuntuVersion: [16.04, 18.04, 20.04]
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # "Fetch" the docker image precached by the "docker-image-cached-build" job that
    # we depend on by re-executing its same steps.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image (cached)
      uses: docker/build-push-action@v2
      with:
        build-args: UbuntuVersion=${{ matrix.UbuntuVersion }}
        tags: mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
          docker.pkg.github.com/microsoft/mlos/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
        #cache-to: type=local,dest=/tmp/.buildx-cache
        load: true
    # Now start an instance of that container image.
    - name: Start ${{ matrix.configuration }} docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
      shell: bash
      run: |
        docker run -it -d -v $PWD:/src/MLOS --env CONFIGURATION=${{ matrix.configuration }} \
          --name mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} \
          mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
    - name: Run ${{ matrix.configuration }} dotnet build
      timeout-minutes: 5
      shell: bash
      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make dotnet-build
    - name: Run ${{ matrix.configuration }} dotnet test
      timeout-minutes: 5
      shell: bash
      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make dotnet-test
    - name: Run ${{ matrix.configuration }} cmake build
      timeout-minutes: 5
      shell: bash
      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make cmake-build
    - name: Run ${{ matrix.configuration }} cmake test
      timeout-minutes: 5
      shell: bash
      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} make cmake-test
    - name: Run cake build
      timeout-minutes: 10
      shell: bash
      run: docker exec mlos-${{ matrix.configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }} ./build.linux.sh
    - name: Cleanup ${{ matrix.configuration }} docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
      shell: bash
      run: |
        docker stop mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }}
        docker rm mlos-${{ matrix.Configuration }}-build-ubuntu-${{ matrix.UbuntuVersion }}

  # Check in-repo markdown links
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        folder-path: './documentation, ./build, ./source, ./test, ./scripts'
        file-path: './CODE_OF_CONDUCT.md, ./CONTRIBUTING.md, ./README.md, ./SECURITY.md'

  build-publish-website:
    name: Build and publish website
    needs: [docker-registry-name, docker-image-cached-build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We only need to run this on one UbuntuVersion (latest), but reusing
        # the matrix like this allows for easier copy/paste of the build-setup
        # steps.
        UbuntuVersion: [20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # "Fetch" the docker image precached by the "docker-image-cached-build" job that
    # we depend on by re-executing its same steps.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image (cached)
      uses: docker/build-push-action@v2
      with:
        build-args: UbuntuVersion=${{ matrix.UbuntuVersion }}
        tags: mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
          docker.pkg.github.com/microsoft/mlos/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
        #cache-to: type=local,dest=/tmp/.buildx-cache
        load: true
    # Now start an instance of that container image.
    - name: Start docker instance
      shell: bash
      run: |
        docker run -it -d -v $PWD:/src/MLOS \
          --name mlos-build \
          mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
    - name: Generate Python API docs using sphinx
      run: docker exec mlos-build make -C website sphinx-site
    - name: Generate main site from markdown using hugo
      run: docker exec mlos-build make -C website hugo-site
    - name: Test the links in the output site
      run: docker exec mlos-build make -C website link-check
    - name: Deploy to GitHub pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        BRANCH: gh-pages
        FOLDER: website/public
    - name: Cleanup docker instance
      shell: bash
      run: |
        docker stop mlos-build
        docker rm mlos-build

  # The licenseheaders check depends on comparing the source tree, so we keep it in a
  # separate pipeline to ensure it starts from a clean state.
  # For simplicity, we only run this one on ubuntu.

  python-licenseheaders-checks:
    name: Check for license header comments on python files
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install licenseheaders
    - name: Run licenseheaders tool and check to see if it caused any changes
      shell: bash
      run: |
        scripts/update-python-license-headers.sh
        # Note: licenseheaders currently rewrites the line-endings from crlf to lf,
        # so we instruct git-diff to ignore those when considering changes.
        git --no-pager diff --ignore-cr-at-eol --exit-code

  # FIXME: These timeouts are egregiously long right now.
  # See Also: https://github.com/microsoft/MLOS/pull/66#issuecomment-690760863
  windows-python-checks:
    name: Run Python checks on Windows
    runs-on: windows-2019
    timeout-minutes: 30
    strategy:
      matrix:
        # FIXME: MLOS currently fails pylint checks for 3.8
        # See Also: https://github.com/microsoft/MLOS/issues/54
        python-version: [3.7] #, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r source/Mlos.Python/requirements.txt
    - name: Run pylint checks (Windows)
      timeout-minutes: 2
      run: scripts\run-python-checks.cmd
    - name: Run Python unit tests (Windows)
      timeout-minutes: 30
      run: scripts\run-python-tests.cmd

  linux-python-checks:
    name: Run Python checks on Ubuntu ${{ matrix.UbuntuVersion }}
    runs-on: ubuntu-latest
    needs: [docker-registry-name, docker-image-cached-build]
    timeout-minutes: 30
    strategy:
      matrix:
        UbuntuVersion: [16.04, 18.04, 20.04]
        # TODO: add support for checking different versions of Python
        # Right now, we install Python 3.7 in the container and default to
        # using it if available, else fallback to the system python3.
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # "Fetch" the docker image precached by the "docker-image-cached-build" job that
    # we depend on by re-executing its same steps.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image (cached)
      uses: docker/build-push-action@v2
      with:
        build-args: UbuntuVersion=${{ matrix.UbuntuVersion }}
        tags: mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
          docker.pkg.github.com/microsoft/mlos/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
        #cache-to: type=local,dest=/tmp/.buildx-cache
        load: true
    # Now, start the image as a new container instance.
    - name: Start docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
      # These images are expected to have installed all the pip dependencies already.
      shell: bash
      run: |
        docker run -it -d -v $PWD:/src/MLOS \
          --name mlos-build-ubuntu-${{ matrix.UbuntuVersion }} \
          mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
    - name: Run pylint checks (Ubuntu ${{ matrix.UbuntuVersion}})
      timeout-minutes: 2
      run: docker exec mlos-build-ubuntu-${{ matrix.UbuntuVersion }} make python-checks
    - name: Run Python unit tests (Ubuntu ${{ matrix.UbuntuVersion}})
      timeout-minutes: 30
      run: docker exec mlos-build-ubuntu-${{ matrix.UbuntuVersion }} make python-test
    - name: Cleanup docker instance for Ubuntu ${{ matrix.UbuntuVersion }}
      shell: bash
      run: |
        docker stop mlos-build-ubuntu-${{ matrix.UbuntuVersion }}
        docker rm mlos-build-ubuntu-${{ matrix.UbuntuVersion }}

  docker-image-publish:
    name: Publish Ubuntu ${{ matrix.UbuntuVersion }} image
    # Only do this if this was a successful merge to the main branch.
    if: ${{ github.ref == 'refs/heads/main' }}
    # And make sure that all of the other tests have passed first.
    needs: [docker-registry-name, docker-image-fresh-build, docker-image-cached-build, linux-build-test, linux-python-checks, build-publish-website]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        UbuntuVersion: [16.04, 18.04, 20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # "Fetch" the docker image precached by the "docker-image-cached-build" job that
    # we depend on by re-executing its same steps.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.UbuntuVersion }}-
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Retrieve the image from the prebuilt cache and push it to the target repo.
      uses: docker/build-push-action@v2
      with:
        build-args: UbuntuVersion=${{ matrix.UbuntuVersion }}
        tags: mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }}
        cache-from: |
          type=local,src=/tmp/.buildx-cache
          ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
          docker.pkg.github.com/microsoft/mlos/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
        cache-to: type=local,dest=/tmp/.buildx-cache
        load: true
    # Now we can push the image to the local docker package repository.
    - name: Push the docker image
      timeout-minutes: 15
      shell: bash
      run: |
        docker tag mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:${{ github.sha }} \
          ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
        docker push ${{ needs.docker-registry-name.outputs.tolower }}/mlos-build-ubuntu-${{ matrix.UbuntuVersion }}:latest
