name: MLOS Markdown Link Check

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Manual MLOS Markdown Link Check run
  push:
    branches: [ main_mlos-core ]  # FIXME: switch to main
  pull_request:
    branches: [ main_mlos-core ]  # FIXME: switch to main

jobs:
  # Check in-repo markdown links
  markdown-link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        use-verbose-mode: no
        folder-path: './doc, ./mlos_core, ./mlos_bench, ./.devcontainer'
        file-path: './CODE_OF_CONDUCT.md, ./CONTRIBUTING.md, ./README.md, ./SECURITY.md'
